# Generated by Django 6.0.4 on 2026-05-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_types',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
