# Generated by Django 6.0.5 on 2026-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_timestamp_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('payment', 'Payment'), ('stake', 'Stake'), ('withdraw', 'Withdraw'), ('refund', 'Refund')], max_length=10),
        ),
    ]
