# Generated by Django 6.0.4 on 2026-05-13 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_gameaccess_game_remove_gameaccess_user_match_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_active',
        ),
        migrations.AddField(
            model_name='match',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Opponent'), ('active', 'In Progress'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='total_rounds',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_field',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('wrong_answers', models.PositiveSmallIntegerField(default=0)),
                ('time_taken', models.FloatField(default=0.0)),
                ('fastest_answer', models.FloatField(blank=True, null=True)),
                ('slowest_answer', models.FloatField(blank=True, null=True)),
                ('rounds_won', models.PositiveSmallIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
