# Generated by Django 6.0.4 on 2026-05-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_match_player2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='created_at',
            new_name='started_at',
        ),
    ]
