# Generated by Django 6.0.4 on 2026-05-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rename_created_at_match_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('answer', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='total_rounds',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
