# Generated by Django 6.0.4 on 2026-05-16 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_puzzel_alter_match_total_rounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveBigIntegerField(default=0)),
                ('numbers', models.JSONField()),
                ('correct_answer', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.match')),
            ],
        ),
        migrations.DeleteModel(
            name='Puzzel',
        ),
    ]
