# Generated by Django 6.0.4 on 2026-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_createround_delete_matchround'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateRound',
            new_name='MatchRound',
        ),
    ]
